DATA TMP_DATAS;
FORMAT DT_COMPRA DATE9.;
INFORMAT DT_COMPRA DATE9.;
INPUT DT_COMPRA;
DATALINES;
01JAN2018
01FEB2018
01MAR2018
01APR2018
;
RUN;

PROC SQL;

CREATE TABLE TMP_PERIODO AS
SELECT PUT(DT_COMPRA, yymmn6.) /* TRANSFORMA DATE9 EM YYYYMM */
FROM TMP_DATAS;

QUIT;