OPTIONS
    REUSE       = YES
    OBS         = MAX
    MSGLEVEL    = I
    BUFNO       = 10
    SYMBOLGEN;

%LET RC=%SYSFUNC(GRDSVC_ENABLE(_WRKLL_,SERVER=SASAPPEG));
OPTIONS AUTOSIGNON;

LIBNAME _WRK &sasworklocation; /* CREATE LIBNAME IN THE SAS WORK LOCATION */

DATA _WRK.TMP_DADOS; * CREATE SAMPLE DATASET;
  DO I=1 TO 1000000;
     OUTPUT;
  END;
RUN;

RSUBMIT TASK1 WAIT=NO SYSRPUTSYNC=YES INHERITLIB=(_WRK); * RUNNING TASK IN PARALLEL;
  DATA _WRK.TMP_TASK1;
     SYSECHO "TASK 1";
     SET _WRK.TMP_DADOS;
     HORA = PUT (TIME(),TIME.);
  RUN;
ENDRSUBMIT;

RSUBMIT TASK2 WAIT=NO SYSRPUTSYNC=YES INHERITLIB=(_WRK); * RUNNING TASK IN PARALLEL;
  DATA _WRK.TMP_TASK2;
     SYSECHO "TASK 2";
     SET _WRK.TMP_DADOS;
     HORA = PUT (TIME(),TIME.);
  RUN;
ENDRSUBMIT;

RSUBMIT TASK3 WAIT=NO SYSRPUTSYNC=YES INHERITLIB=(_WRK);* RUNNING TASK IN PARALLEL;
  DATA _WRK.TMP_TASK3;
     SYSECHO "TASK 3";
     SET _WRK.TMP_DADOS;
     HORA = PUT (TIME(),TIME.);
  RUN;
ENDRSUBMIT;

SYSECHO "WAIT...";

WAITFOR _WRKLL_ TASK1 TASK2 TASK3;
SIGNOFF TASK1;
SIGNOFF TASK2;
SIGNOFF TASK3;
