%MACRO RAND_BETWEEN(MIN, MAX); /* CREATE MACRO TO GENEREATE A RANGE RANDOM NUMBER; */
   (&MIN + FLOOR((1+&MAX-&MIN)*RAND("UNIFORM")));
%MEND;

DATA TMP_BIG_TABLE; * CREATE A BIG TABLE OF PRODUCTS SALE;
  DO ID_SALE=1 TO 1000000;
     ID_PRODUCT = %RAND_BETWEEN(1,5);     
     OUTPUT;
  END;
RUN;
